name: Continuous Integration

on:
  push:
    branches:
    - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
    - run: yarn install
    - run: yarn run build 
    - name: run component tests
      run: yarn run test:component
    - name: run contract tests
      run: yarn run test:contract
      env:
        API: ${{secrets.REACT_APP_API}}
    - name: publish contracts
      env:
        PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
        PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
        PACT_CONSUMER_VERSION: ${{secrets.PACT_CONSUMER_VERSION}}
      run: yarn run test:contract:publish
